-- Rename back the STUDENTS.STUDENT_ID to STUDENTS.ST_ID 
ALTER TABLE STUDENTS RENAME COLUMN STUDENT_ID TO ST_ID;
SELECT * from STUDENTS;

-- Change back the length of STUDENTS.ST_NAME and STUDENTS.ST_LAST from 30 to 20
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(20);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(20);

-- Change back INTERESTS table
CREATE TABLE OLD_VERSION_INTERESTS (
    STUDENT_ID INTEGER REFERENCES STUDENTS(ST_ID),
    INTEREST VARCHAR(20)
);

SELECT * from INTEREST;
SELECT * from OLD_VERSION_INTERESTS;

INSERT INTO OLD_VERSION_INTERESTS (STUDENT_ID, INTEREST)
SELECT STUDENT_ID, UNNEST(INTEREST) 
FROM INTEREST;

DROP TABLE INTEREST;
ALTER TABLE OLD_VERSION_INTERESTS RENAME TO INTERESTS; 
SELECT * from INTERESTS;
